Install wget to avoid the busybox wget leaking defunct processes
distribution/distribution-library-image pull request #159
Opened 2024-03-04 14:53 UTC by aleskandro

When running busybox wget v1.31.x to request an SSL page, there is a leak of defunct processes that eventually could hit the limit for fork syscalls, leading to the unavailability of main registry process.

Installing wget from the alpine repository resolves the issue as this only affects the busybox distribution. Moreover, this should transparently resolve the issue for deployments
using wget as healthcheck/readiness/liveness probe.

xref: https://bugs.busybox.net/show_bug.cgi?id=15967

Closes #158

2024-03-04 17:39 UTC, milosgajdos commented
Please sign your commit.

2024-03-04 17:44 UTC, aleskandro commented
Done!

2024-03-04 17:48 UTC, milosgajdos approved these changes
Why is busybox binary packed into alpine image kinda breaks my solar system brain -- I guess the galaxy brains that made this decision see something I can't.

Thanks for the fix. PTAL @thaJeztah

2024-03-04 19:21 UTC, thaJeztah commented
This `wget` binary is only used during build of the Dockerfile; as far as I can see, it's not used in the final image, unless someone decides to use it (I see some issues linked that use it in a healthcheck).

All of that is custom, so I don't think we must install wget by default; it's not part of the main requirements of the image to run, and if needed should be installed by the user (extending the image)

2024-03-04 19:27 UTC, thaJeztah requested changes
(see comment above)

2024-03-04 20:16 UTC, aleskandro commented
Hi @theJeztah

> unless someone decides to use it (I see some issues linked that use it in a healthcheck).
> 
> All of that is custom, so I don't think we must install wget by default; it's not part of the main requirements of the image to run, and if needed should be installed by the user (extending the image)

Hi @thaJeztah, thanks for the quick reply. I get it, and the best would be to have the wget busybox applet fixed. However, as of today, there's no way for this image to execute a healthcheck of the registry as no tool is available to run HTTP(s) requests, except the bugged `wget`.

Is there another way users can exploit to execute an in-container healthcheck without extending the image?

The following are leaked zombie processes left by the wget currently available in the image:
```
└ $ docker exec -it myreg ps aux                                       
PID   USER     TIME  COMMAND
    1 root      0:00 registry serve /etc/docker/registry/config.yml
   40 root      0:00 [ssl_client]
   41 root      0:00 [ssl_client]
   74 root      0:00 [ssl_client]
   75 root      0:00 [ssl_client]
   88 root      0:00 [ssl_client]
   89 root      0:00 [ssl_client]
  102 root      0:00 [ssl_client]
  103 root      0:00 [ssl_client]
  104 root      0:00 ps aux
```

2024-03-04 20:47 UTC, milosgajdos commented
Is there any reason why you do in-container health checks and not leveraging some "higher leve/external/orchestration" means? I suspect the lure is the `HEALTH` Dockerfile instruction https://docs.docker.com/reference/dockerfile/#healthcheck?

2024-03-04 21:07 UTC, schildbach commented
> Is there any reason why you do in-container health checks and not leveraging some "higher leve/external/orchestration" means? I suspect the lure is the `HEALTH` Dockerfile instruction https://docs.docker.com/reference/dockerfile/#healthcheck?

Docker/Compose health checks are similar to `docker exec`; the referenced executable needs to be available inside the container.

2024-03-04 21:28 UTC, milosgajdos commented
@schildbach oh, I'm not saying there is anything wrong with the request - in fact I've approved the PR - I'm just curious.

@thaJeztah the current wget binary is clearly DOS-ing the service when used in healthchecks. This needs fixing.

2024-03-05 13:26 UTC, thaJeztah commented
> xref: https://bugs.busybox.net/show_bug.cgi?id=15967

Before I forget to mention; I think Alpine ships with its own fork of busybox (I recall that they carry various patches which may not (yet) have been accepted in upstream: https://git.alpinelinux.org/aports/tree/main/busybox?h=master); so it may also be worth opening a ticket in Alpine's issue tracker for this.

> Why is busybox binary packed into alpine image kinda breaks my solar system brain -- I guess the galaxy brains that made this decision see something I can't.

I think the busybox binary in alpine is purely as a most-minimal "bootstrap" for the image; provide a minimal userland (a shell, and some common utilities provided by busybox), but adding Alpines package-manager to install the _actual_ tools you may need after that.

2024-03-05 13:45 UTC, aleskandro commented
Thanks @thaJeztah, in the specific case of the registry, it is the registry itself to be the PID1. Should we consider a fix in the registry also to handle the related signals?

2024-03-05 15:28 UTC, thaJeztah commented
> Should we consider a fix in the registry also to handle the related signals?

Heh, just had a lengthy chat in our internal Slack discussing this case because it's really a bit of a grey area, and to some amount a matter of "semantics";

- `--init` should normally be considered an "escape hatch" for a PID1 in a container misbehaving (if process is running as PID1, it should properly handle cleanup)
- The grey area here is that `registry` (as far as I can see) is not "misbehaving"; it _does_ handle what it's expected to do; run a registry, and handle that. It's not expected to do more than that, or not expected to handle processes it didn't create.
- The situation happening here is that something went behind its back and shoved some processes underneath it, and those processes (seemingly) expecting something else to handle reaping.

From your earlier descriptions of busybox, I still feel it's a bug in busybox (which, after all, spins up the processes); pending that to be fixed, `--init` can be a proper workaround (or installing a different tool for the job, such as the `apk add wget`). From the perspective of the `registry`'s core responsibility, adding that functionality to the `registry` code would be an "enhancement", not so much a bugfix, and (TBD) could be considered out of scope of its feature-set.

If the busybox maintainer consider it to not be a bug (perhaps it was not designed to be invoked this way?), and _IF_ using the default `wget` is expected to be the default way to perform health-checks in this image, then an alternative could be to include `tini` in the container as PID1 to make sure the image has a reaper by default.

2024-03-05 15:38 UTC, aleskandro commented
> From your earlier descriptions of busybox, I still feel it's a bug in busybox 

Agreed 100%. All the discussion here is to have a solution until the bug is fixed upstream and downstream by the distros (I'd say it's in the upstream busybox, if not already fixed in the next versions, as the same issue happens on the ubuntu's build). 

> If the busybox maintainer consider it to not be a bug (perhaps it was not designed to be invoked this way?), and IF using the default wget is expected to be the default way to perform health-checks in this image, then an alternative could be to include tini in the container as PID1 to make sure the image has a reaper by default.

yeah, the point for the registry is that it's actually used as PID1 by this image. Although I agree, it would still be like a 'safety' mechanism when PID1 inherits a defunct child process,  as in this case.

Should I close this PR or would we change it to something that is acceptable? I think some of the thoughts in this discussion should go in the issue at least, to inform other potential users making use of wget in a https-backed registry.

2024-03-06 09:35 UTC, milosgajdos commented
> Should I close this PR or would we change it to something that is acceptable? I think some of the thoughts in this discussion should go in the issue at least, to inform other potential users making use of wget for healthchecking an https registry.

I think we should close it as I dont think we'll reach a consensus that will lead to merging this in.

Moving some of the discussed points to the original issue sounds like a good idea but I think it might not be needed as the links to this PR are displayed in the GH UI so I'd just leave it as is.

2024-03-06 09:36 UTC, closed without merging